version: '3'
services:
  poster_generator:
    build:
      context: .
    ports:
      - $LOCAL_PORT:80
    volumes:
      - type: volume
        source: json
        target: /poster_generator_json:rw
        volume:
          nocopy: true
    networks:
      - poster_generator_network
    tmpfs:
      - /tmp:rw
volumes:
  json:
networks:
  poster_generator_network:
    driver: bridge
