name: Main tests

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

permissions:
  contents: read

jobs:
  main-tests:
    permissions:
      contents: write

    environment: Production

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y php mysql-server
        sudo apt install mariadb-server
        pwd
        echo ${{ runner.TOOL_CACHE }}

    - uses: getong/mariadb-action@v1.11
      with:
        host port: 3800
        container port: 3307
        character set server: 'utf8'
        collation server: 'utf8_general_ci'
        mariadb version: '10.4.10'
        mysql database: 'some_test'
        mysql root password: password
        mysql user: 'poster_generator'
        mysql password: password

    - name: Run test script
      run: |
        ./tests/test_env

    - name: Create a new version
      if: ${{ success() }}
      run: |
        echo "Creating new version"
        git tag ${{ github.run_number }} || true
        git push origin --tags || true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: tests/test_report.json

    - name: Archive Changed Database After Tests
      uses: actions/upload-artifact@v4
      with:
        name: store-post-test-sql
        path: tests/post_test.sql
