name: Main tests

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

permissions:
  contents: read

env:
  DB_USER: 'poster_generator'

jobs:
  main-tests:
    permissions:
      contents: write

    environment: Production

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Grand folder permissions
      run: |
        sudo chmod a+rwX /var/cache/apt/archives
        ls -ld /var/cache/apt/archives


    - name: Cache APT packages
      id: apt-cache
      uses: actions/cache@v4
      with:
        path: /var/cache/apt/archives
        key: apt-packages-${{ runner.os }}-${{ hashFiles('.github/workflows/main.yml') }}
        restore-keys: |
          apt-packages-${{ runner.os }}-

    # - name: Move cached packages back
    #   run: |
    #     sudo cp ./apt-cache/*.deb /var/cache/apt/archives/ || true

    - name: Install dependencies
      if: steps.apt-cache.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt install mariadb-server
        pip install selenium
        pip install mypy

        echo $'Package: *\nPin: release o=LP-PPA-mozillateam\nPin-Priority: 1001' | sudo tee /etc/apt/preferences.d/mozilla-firefox
        sudo add-apt-repository -y ppa:mozillateam/ppa
        sudo apt-get update
        sudo apt-get install -y firefox
        sudo apt-get install -y libx11-xcb-dev libxcb1-dev libdbus-1-3 libxtst6 libnss3 libgdk-pixbuf2.0-0

        GECKO_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep -o '"tag_name":"[^"]*"' | sed 's/"tag_name":"//;s/"$//')
        echo $GECKO_VERSION
        echo -----
        [[ $GECKO_VERSION='' ]] && GECKO_VERSION='v0.36.0'
        echo $GECKO_VERSION
        wget https://github.com/mozilla/geckodriver/releases/download/$GECKO_VERSION/geckodriver-$GECKO_VERSION-linux64.tar.gz
        tar -xzf geckodriver-$GECKO_VERSION-linux64.tar.gz
        chmod +x geckodriver
        sudo mv geckodriver /usr/local/bin/

    - name: Grand folder permissions 2
      run: |
        sudo chmod +rwx /var/cache/apt/archives/lock
        sudo chmod +rwX /var/cache/apt/archives/partial

    # - name: Copy APT cache to workspace
    #   run: |
    #     mkdir -p ./apt-cache
    #     sudo cp /var/cache/apt/archives/*.deb ./apt-cache/


    # - name: Pull MariaDB image manually
    #   run: docker pull mariadb:latest

    - uses: getong/mariadb-action@v1.11
      with:
        host port: 3800
        container port: 3307
        character set server: 'utf8'
        collation server: 'utf8_general_ci'
        mariadb version: '10.4.10'
        mysql database: 'some_test'
        mysql root password: password
        mysql user: ${{ env.DB_USER }}
        mysql password: password

    - name: Manage Server
      run: |
        php -S 0.0.0.0:8080 -t /home/runner/work/scientific_poster_generator &
        sleep 5
        netstat -tuln
        ps aux | grep php

    - name: Run test script
      run: |
        curl -v http://127.0.0.1:8080/scientific_poster_generator/login.php
        echo -----------------
        ./tests/test_env
        ls -l /var/cache/apt/archives
        echo ---
        ls -ld /var/cache/apt/archives/partial


    - name: Create a new version
      if: ${{ success() }}
      run: |
        echo "Creating new version"
        git tag ${{ github.run_number }} || true
        git push origin --tags || true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: tests/test_report.json

    - name: Archive Changed Database After Tests
      uses: actions/upload-artifact@v4
      with:
        name: store-post-test-sql
        path: tests/post_test.sql
